import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:8080/');
  await page.getByRole('link', { name: 'Sign In' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('demo');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('demo');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.locator('.icon > .fa').first().click();
  await page.getByRole('link', { name: 'More info ' }).first().click();
  await page.getByRole('button', { name: ' Previous' }).click();
  await page.getByRole('link', { name: ' Students' }).click();
  await page.getByRole('textbox', { name: 'Quick Search' }).click();
  await page.getByRole('link', { name: ' Courses' }).click();
  await page.getByRole('link', { name: ' Attendance Record' }).click();
  await page.getByRole('link', { name: ' Academic Year' }).click();
  await page.getByRole('link', { name: ' Marks' }).click();
  await page.getByRole('link', { name: ' Dashboard' }).click();
  await page.getByRole('link', { name: 'More info ' }).nth(1).click();
  await page.getByRole('link', { name: ' Attendance Record' }).click();
  await page.locator('#attendance-student-1').getByRole('link', { name: 'Anwar Moha' }).click();
  await page.getByRole('button', { name: ' Back' }).click();
  await page.getByRole('link', { name: ' ACTIONS ' }).click();
  await page.getByRole('link', { name: ' Dashboard' }).click();
  await page.getByRole('paragraph').filter({ hasText: 'Marks' }).click();
  await page.getByRole('link', { name: 'More info ' }).nth(3).click();
  await page.getByRole('link', { name: ' ACTIONS ' }).click();
  await page.getByRole('link', { name: ' Sign Out' }).click();
  await page.getByRole('textbox', { name: 'Username' }).click();
  await page.getByRole('textbox', { name: 'Username' }).fill('ronald');
  await page.getByRole('textbox', { name: 'Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('ronald');
  await page.getByRole('button', { name: 'Sign In' }).click();
  await page.getByRole('link', { name: ' Admin Area' }).click();
  await page.getByRole('link', { name: ' Members' }).click();
  await page.getByRole('link', { name: 'User\'s area' }).click();
  await page.getByRole('link', { name: ' Admin Area' }).click();
  await page.getByRole('link', { name: ' Groups' }).click();
  await page.getByRole('link', { name: ' Groups' }).click();
  await page.getByRole('link', { name: ' Members' }).click();
  await page.getByRole('link', { name: ' Members' }).click();
  await page.getByRole('link', { name: ' Utilities' }).click();
  await page.getByRole('link', { name: ' Sign out' }).click();
});
